### ISSUE TITLE
Support for icon fonts?

### ISSUE THREAD

**Issue by calculuschild** [UziTech/marked-emoji#246]
What are your thoughts on adding support for icon fonts like FontAwesome, etc.? In this case, the key/value pair would be an emoji name, and css class(es), rather than an image url:

```javascript
{
"eye"  : "fa-solid fa-eye",
"flask" : "fa-solid fa-flask",
...
}
```

The output would be something along the lines of:

```html
<i class="fa-solid fa-eye"></i>
```

Where `fa-solid fa-eye` would be defined in an external .css file (generally supplied by the font creator):

```css
@font-face {
  font-family : 'Font-Awesome';
  src : url('./fontAwesome.woff2');
} 

fa-solid fa-eye:before { content: '\f108'; }
fa-solid fa-flask:before { content: '\f109'; }
...
```
